### ISSUE TITLE
No syntax highlighting from .reg of a Win 10 with vscode 1.20.1

### ISSUE THREAD

**Issue by CailleauThierry** [ionutvmi/reg-vscode#2]
With a .reg generated from a windows 10 Laptop i do not see any syntax highlighting with tis plugin installed (just installed it from vscode Extensions) today 02/21/2018

**Comment by mihai-vlc** [comment]
Do you have reg selected in the bottom right corner of the screen ?
![image](https://user-images.githubusercontent.com/3531898/36527837-d245b890-17bb-11e8-96dc-0ce28945cf4e.png)

**Comment by CailleauThierry** [comment]
Sorry fr the delay in response. Yes "REG" is selected:
![image](https://user-images.githubusercontent.com/19176129/36636121-0a8c517c-19c0-11e8-91e3-636904f1de04.png)

![image](https://user-images.githubusercontent.com/19176129/36636141-4601324a-19c0-11e8-9c8e-a02677b5a6d8.png)

![image](https://user-images.githubusercontent.com/19176129/36636143-578db0b0-19c0-11e8-8be6-dd887bde8681.png)

It does not work on my Win 10 Laptop with either .reg generated from my laptop or with .reg generated from another machine

**Comment by mihai-vlc** [comment]
After some investigations it looks like VSCode has some issues with larger files (30M+) and it won't attempt to do the syntax highlight on it.

I would recommend to use another editor for those particular files.

Source: https://code.visualstudio.com/updates/v1_15#_large-file-support
