### ISSUE TITLE
Syntax coloring on pre-5.0 reg files produces nearly unreadable results

### ISSUE THREAD

**Issue by AlanMcBee** [ionutvmi/reg-vscode#3]
I was prompted to install this extension, which I happily did. This is what my .reg file looks like. I'm having great difficulty reading it.

It appears that the extension doesn't support the earlier format of .reg files, even though they are still supported by RegEdit.

![image](https://user-images.githubusercontent.com/37203424/39901077-18c62682-547b-11e8-880e-8428b637f2ef.png)

**Comment by mihai-vlc** [comment]
Can you please post a code snippet of that causes issues for you ?

I will try to reproduce and fix this over the weekend.

**Comment by AlanMcBee** [comment]
You know, I was moving fast and didn't take a good enough look at the file. It's not a valid REGEDIT4 file. I'll close this.

**Comment by AlanMcBee** [comment]
Closed because the file used to test was not a valid REGEDIT4 file.
